#!/usr/bin/env bash
# src/lib/00h-multi-agent.sh — Multi-Agent Targets Generator (v4.0.0)
# Generates configuration files for various AI coding assistants:
# - .github/copilot-instructions.md (GitHub Copilot)
# - .claude/settings.json (Anthropic Claude)
# - .cursor/settings.json (Cursor)
# - .opencode/agents/ (OpenCode agents)
# Sources: src/lib/00-core.sh must be sourced before this file
set -euo pipefail

# ── Multi-agent configuration ────────────────────────────────────────────────
_PROJECT_DIR="${PROJECT_DIR:-.}"

# ── Generate GitHub Copilot instructions ─────────────────────────────────────
# Usage: _generate_copilot_instructions [project_dir]
_generate_copilot_instructions() {
  local project_dir="${1:-$_PROJECT_DIR}"
  local output="$project_dir/.github/copilot-instructions.md"
  local now
  now=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

  mkdir -p "$project_dir/.github"

  cat > "$output" <<EOF
# GitHub Copilot Instructions

> Auto-generated by opencode_initializer v${SCRIPT_VERSION:-v4.0.0}
> Generated: $now

## Project Overview

This is an AI-powered developer machine bootstrapper that sets up a complete
development environment with 6+ languages, 24 MCP servers, 22 AI providers,
and infrastructure as code.

## Code Style

### Shell Scripts
- Use \`set -euo pipefail\` at the top of every script
- Use \`shellcheck\` for linting
- Functions: \`_snake_case\` with underscore prefix for private functions
- Variables: \`UPPER_CASE\` for exports, \`snake_case\` for locals
- Constants: \`readonly UPPER_CASE\`
- Error handling: \`trap '_trap_cleanup "module"' ERR\`

### Naming Conventions
- Module files: \`NN-module-name.sh\` (two-digit prefix)
- Test files: \`test_module_name.sh\`
- Config files: \`setup.toml\`, \`setup.conf\`

### Documentation
- Bilingual: English (.en.md) + Russian (.ru.md) pairs
- ADRs in \`docs/adr/\`
- Runbooks in \`docs/runbooks/\`

## Architecture

### Module Structure
\`\`\`
src/lib/
├── 00-core.sh          # Core infrastructure
├── 00d-parallel.sh     # Parallel installation engine
├── 00e-cache-mgr.sh    # Download cache manager
├── 00f-apm.sh          # APM preparation
├── 01-system.sh        # System packages
├── 02-docker.sh        # Docker engine
├── NN-module.sh        # Feature modules
└── helpers.sh          # Shared utilities
\`\`\`

### Key Patterns
1. **WAL (Write-Ahead Log)**: All state changes logged to \`wal.md\`
2. **Progress Tracking**: Resume after failure via \`progress\` file
3. **Parallel Execution**: Layer-based with dependency awareness
4. **Idempotent**: All modules safe to re-run

### Testing
- Unit tests: \`tests/unit/test_*.sh\`
- Integration tests: \`tests/integration/test_*.py\`
- E2E tests: \`tests/e2e/\`

## Common Tasks

### Adding a New Module
1. Create \`src/lib/NN-module-name.sh\`
2. Add \`_run_step\` call in \`setup.sh\`
3. Create \`tests/unit/test_module_name.sh\`
4. Update \`README.md\` and \`README.ru.md\`

### Running Tests
\`\`\`bash
# All tests
bash tests/run-all.sh

# Single test
bash tests/unit/test_core.sh

# With coverage
bash tests/run-all.sh --coverage
\`\`\`

### Debugging
\`\`\`bash
# Dry run
./setup.sh --dry-run

# Health check
./setup.sh --health

# State detection
./dev.sh state
\`\`\`

## AI Provider Integration

### Supported Providers
- DeepSeek, OpenAI, Anthropic, Google, xAI, MiniMax, MiMo
- Alibaba Qwen, DeepInfra, Groq, Together, Fireworks
- Perplexity, Mistral, Cohere, Cerebras
- OpenRouter (aggregator)
- z.ai GLM-5.2 (RU/CN markets)

### Configuration
Provider keys in \`~/.config/opencode/secrets.env\`:
\`\`\`bash
DEEPSEEK_KEY=sk-...
OPENAI_API_KEY=sk-...
ANTHROPIC_API_KEY=sk-ant-...
\`\`\`

## Infrastructure

### Docker Services
- PostgreSQL 17 (port 5432)
- Qdrant (port 6333)
- Redis (port 6379)
- Prometheus (port 9090)
- Grafana (port 3001)
- MemoryLayer (port 61001)

### Management
\`\`\`bash
# Start all services
docker compose -f docker-compose.yml up -d

# Health check
./dev.sh health

# Logs
docker compose logs -f
\`\`\`
EOF

  log "Copilot instructions generated: $output"
}

# ── Generate Claude settings ─────────────────────────────────────────────────
# Usage: _generate_claude_settings [project_dir]
_generate_claude_settings() {
  local project_dir="${1:-$_PROJECT_DIR}"
  local output="$project_dir/.claude/settings.json"
  local now
  now=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

  mkdir -p "$project_dir/.claude"

  cat > "$output" <<EOF
{
  "version": "1.0.0",
  "generated": "$now",
  "generator": "opencode_initializer v${SCRIPT_VERSION:-v4.0.0}",
  "project": {
    "name": "opencode_initializer",
    "type": "developer-tools",
    "language": "bash",
    "framework": "shell-scripts"
  },
  "instructions": "This is an AI-powered developer machine bootstrapper. Follow shell best practices, use set -euo pipefail, and maintain bilingual documentation (EN/RU).",
  "preferences": {
    "code_style": {
      "indentation": 2,
      "line_length": 120,
      "naming": "snake_case",
      "comments": "explain why, not what"
    },
    "documentation": {
      "language": "bilingual",
      "format": "markdown",
      "include_examples": true
    },
    "testing": {
      "framework": "bash-assert",
      "coverage_target": 80,
      "test_pattern": "test_*.sh"
    }
  },
  "tools": {
    "shellcheck": {
      "enabled": true,
      "severity": "warning"
    },
    "shfmt": {
      "enabled": true,
      "style": "google"
    }
  },
  "security": {
    "scan_secrets": true,
    "verify_checksums": true,
    "sandbox_mode": false
  }
}
EOF

  log "Claude settings generated: $output"
}

# ── Generate Cursor settings ─────────────────────────────────────────────────
# Usage: _generate_cursor_settings [project_dir]
_generate_cursor_settings() {
  local project_dir="${1:-$_PROJECT_DIR}"
  local output="$project_dir/.cursor/settings.json"
  local now
  now=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

  mkdir -p "$project_dir/.cursor"

  cat > "$output" <<EOF
{
  "version": "1.0.0",
  "generated": "$now",
  "generator": "opencode_initializer v${SCRIPT_VERSION:-v4.0.0}",
  "project": {
    "name": "opencode_initializer",
    "type": "developer-tools",
    "language": "bash"
  },
  "ai": {
    "model": "claude-3.5-sonnet",
    "context_window": 200000,
    "instructions": "This is an AI-powered developer machine bootstrapper. Follow shell best practices, use set -euo pipefail, and maintain bilingual documentation (EN/RU).",
    "code_style": {
      "indentation": 2,
      "line_length": 120,
      "naming": "snake_case"
    }
  },
  "editor": {
    "tab_size": 2,
    "insert_spaces": true,
    "word_wrap": "off",
    "line_numbers": true,
    "minimap": false
  },
  "terminal": {
    "shell": "/bin/bash",
    "shell_args": ["-e", "-u", "-o", "pipefail"]
  },
  "files": {
    "associations": {
      "*.sh": "shellscript",
      "*.bash": "shellscript",
      "setup.toml": "toml",
      "setup.conf": "properties"
    },
    "exclude": [
      "**/node_modules",
      "**/.cache",
      "**/dist"
    ]
  },
  "search": {
    "exclude": [
      "**/node_modules",
      "**/.cache",
      "**/dist",
      "**/*.log"
    ]
  }
}
EOF

  log "Cursor settings generated: $output"
}

# ── Generate VS Code settings ────────────────────────────────────────────────
# Usage: _generate_vscode_settings [project_dir]
_generate_vscode_settings() {
  local project_dir="${1:-$_PROJECT_DIR}"
  local output="$project_dir/.vscode/settings.json"
  local now
  now=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

  mkdir -p "$project_dir/.vscode"

  cat > "$output" <<EOF
{
  "version": "1.0.0",
  "generated": "$now",
  "generator": "opencode_initializer v${SCRIPT_VERSION:-v4.0.0}",
  "editor.tabSize": 2,
  "editor.insertSpaces": true,
  "editor.wordWrap": "off",
  "editor.formatOnSave": true,
  "editor.codeActionsOnSave": {
    "source.fixAll.shellcheck": "explicit"
  },
  "shellcheck.enable": true,
  "shellcheck.run": "onSave",
  "shellcheck.exclude": ["SC2034", "SC2086"],
  "files.associations": {
    "*.sh": "shellscript",
    "*.bash": "shellscript",
    "setup.toml": "toml",
    "setup.conf": "properties"
  },
  "files.exclude": {
    "**/node_modules": true,
    "**/.cache": true,
    "**/dist": true
  },
  "search.exclude": {
    "**/node_modules": true,
    "**/.cache": true,
    "**/dist": true,
    "**/*.log": true
  },
  "terminal.integrated.shell.linux": "/bin/bash",
  "terminal.integrated.shellArgs.linux": ["-e", "-u", "-o", "pipefail"]
}
EOF

  log "VS Code settings generated: $output"
}

# ── Generate all multi-agent targets ─────────────────────────────────────────
# Usage: _generate_all_targets [project_dir]
_generate_all_targets() {
  local project_dir="${1:-$_PROJECT_DIR}"

  section "Multi-Agent Targets Generation"

  _generate_copilot_instructions "$project_dir"
  _generate_claude_settings "$project_dir"
  _generate_cursor_settings "$project_dir"
  _generate_vscode_settings "$project_dir"

  log "All multi-agent targets generated"
  info "  .github/copilot-instructions.md"
  info "  .claude/settings.json"
  info "  .cursor/settings.json"
  info "  .vscode/settings.json"
}

# ── Export functions ─────────────────────────────────────────────────────────
export -f _generate_copilot_instructions _generate_claude_settings \
  _generate_cursor_settings _generate_vscode_settings _generate_all_targets 2>/dev/null || true
