#!/usr/bin/env bash
# lib/50-sandcastle.sh — Sandcastle: sandboxed AI coding agents (STEP 50)
# Sources: https://github.com/mattpocock/sandcastle (research 2026-08-16)
# Sandcastle orchestrates AI coding agents in isolated sandboxes (Docker/Podman/Vercel).
# Providers are swappable; branch strategies + lifecycle hooks; sandcastle.run() API.
set -euo pipefail

_step_skip step_sandcastle && return 0

section "Sandcastle — Sandboxed AI Agents"

SANSCASTLE_DIR="${SANSCASTLE_DIR:-.sandcastle}"

# ── Detect the best available sandbox provider ────────────────────────────────
_sandcastle_provider() {
  if command -v docker &>/dev/null && docker info &>/dev/null 2>&1; then
    echo "docker"
  elif command -v podman &>/dev/null; then
    echo "podman"
  else
    echo "no-sandbox"
  fi
}

# ── Install Sandcastle into the current project ───────────────────────────────
_install_sandcastle() {
  if ! command -v node &>/dev/null; then
    warn "Node.js not found — Sandcastle requires Node.js. Skipping."
    return 0
  fi

  if [ -z "${PROJECT_DIR:-}" ] || [ ! -d "$PROJECT_DIR" ]; then
    warn "PROJECT_DIR not set — Sandcastle is project-scoped. Skipping."
    return 0
  fi

  if [ -d "$PROJECT_DIR/$SANSCASTLE_DIR" ] && [ -f "$PROJECT_DIR/package.json" ]; then
    if grep -q '"@ai-hero/sandcastle"' "$PROJECT_DIR/package.json" 2>/dev/null; then
      log "Sandcastle already installed in $PROJECT_DIR"
      return 0
    fi
  fi

  local provider
  provider="$(_sandcastle_provider)"
  if [ "$provider" = "no-sandbox" ]; then
    warn "Neither Docker nor Podman available — Sandcastle will use 'no-sandbox' provider (agents run on host)"
  fi

  _spin_start "Installing @ai-hero/sandcastle"
  if (cd "$PROJECT_DIR" && timeout 180 npm install --save-dev @ai-hero/sandcastle 2>/dev/null); then
    _spin_stop "✓"
    log "Sandcastle installed (provider: $provider)"
  else
    _spin_stop "✗"
    warn "Sandcastle npm install failed — skipping"
    return 0
  fi

  # Scaffold .sandcastle/ directory via the official init CLI
  if [ -d "$PROJECT_DIR/$SANSCASTLE_DIR" ]; then
    log "Sandcastle scaffold already present in $PROJECT_DIR/$SANSCASTLE_DIR"
  else
    _spin_start "Scaffolding .sandcastle/"
    if (cd "$PROJECT_DIR" && timeout 90 npx --yes @ai-hero/sandcastle init 2>/dev/null); then
      _spin_stop "✓"
      log "Sandcastle scaffolded in $PROJECT_DIR/$SANSCASTLE_DIR"
    else
      _spin_stop "✗"
      warn "Sandcastle init failed — creating minimal scaffold manually"
      _sandcastle_scaffold
    fi
  fi
}

# ── Minimal manual scaffold fallback (init CLI unavailable) ───────────────────
_sandcastle_scaffold() {
  [ -z "${PROJECT_DIR:-}" ] || [ ! -d "$PROJECT_DIR" ] && return 0
  mkdir -p "$PROJECT_DIR/$SANSCASTLE_DIR"
  cat > "$PROJECT_DIR/$SANSCASTLE_DIR/main.ts" << 'MAIN_TS'
// .sandcastle/main.ts — Sandcastle agent runner (generated by opencode_initializer)
// Run with: npx tsx .sandcastle/main.ts
import { run, claudeCode } from "@ai-hero/sandcastle";
import { docker } from "@ai-hero/sandcastle/sandboxes/docker";
import { podman } from "@ai-hero/sandcastle/sandboxes/podman";
import { noSandbox } from "@ai-hero/sandcastle/sandboxes/no-sandbox";

// Pick a sandbox provider: docker(), podman(), or noSandbox() (runs on host).
const sandbox = docker();
// const sandbox = podman();
// const sandbox = noSandbox();

await run({
  agent: claudeCode("claude-opus-4-8"),
  sandbox,
  promptFile: ".sandcastle/prompt.md",
});
MAIN_TS
  cat > "$PROJECT_DIR/$SANSCASTLE_DIR/prompt.md" << 'PROMPT'
# Task

Describe the task for the agent here. Use {{PLACEHOLDER}} keys and pass
them via `promptArgs` in main.ts for templating.

Example: "Fix issue #{{ISSUE_NUMBER}} in this repo."
PROMPT
  log "Minimal Sandcastle scaffold created (main.ts + prompt.md)"
}

# ── Configure Sandcastle (.env auth + provider) ───────────────────────────────
_configure_sandcastle() {
  [ -z "${PROJECT_DIR:-}" ] || [ ! -d "$PROJECT_DIR" ] && return 0
  [ ! -d "$PROJECT_DIR/$SANSCASTLE_DIR" ] && return 0

  local env_file="$PROJECT_DIR/$SANSCASTLE_DIR/.env"
  local env_example="$PROJECT_DIR/$SANSCASTLE_DIR/.env.example"
  local provider
  provider="$(_sandcastle_provider)"

  # Create .env.example template if the init CLI did not provide one
  if [ ! -f "$env_example" ]; then
    cat > "$env_example" << 'ENV_EXAMPLE'
# Sandcastle agent credentials — copy to .env and fill in.
# Generate a Claude Code OAuth token on your host: `claude setup-token`
CLAUDE_CODE_OAUTH_TOKEN=

# Alternative: use an Anthropic API key instead of the OAuth token.
# ANTHROPIC_API_KEY=
ENV_EXAMPLE
  fi

  # Copy template → .env (never overwrite an existing one)
  if [ ! -f "$env_file" ]; then
    cp "$env_example" "$env_file"
    log "Created $SANSCASTLE_DIR/.env from template — fill in CLAUDE_CODE_OAUTH_TOKEN or ANTHROPIC_API_KEY"
  else
    log "Sandcastle .env already present"
  fi

  # Warn if no credentials configured
  if ! grep -qE 'CLAUDE_CODE_OAUTH_TOKEN=.+|ANTHROPIC_API_KEY=.+' "$env_file" 2>/dev/null; then
    info "Sandcastle auth not yet configured — run 'claude setup-token' and set CLAUDE_CODE_OAUTH_TOKEN in $SANSCASTLE_DIR/.env"
  fi

  log "Sandcastle provider: $provider (configure in $SANSCASTLE_DIR/main.ts to override)"
}

# ── Health check ──────────────────────────────────────────────────────────────
_check_sandcastle() {
  if command -v node &>/dev/null && [ -d "${PROJECT_DIR:-}/$SANSCASTLE_DIR" ]; then
    log "Sandcastle — installed (provider: $(_sandcastle_provider))"
    return 0
  fi
  warn "Sandcastle — not installed"
  return 1
}

# Main
_install_sandcastle
_configure_sandcastle

_step_done step_sandcastle
log "Sandcastle sandboxed agents ready — 'npx tsx .sandcastle/main.ts' to run"
