#!/usr/bin/env bash
# lib/56-grace-semantics.sh — GRACE-style semantic contracts & clarity metrics
# (STEP 56)
# Inspired by:
#   - GRACE framework (semantic markup as native interface for LLM-coding)
#   - Polomodov's "контрактное программирование" (contracts as semantic shield)
#   - Firth's distributional linguistics ("You shall know a word by the
#     company it keeps") — meaning is correlation
#   - Cybenko universal approximation — large nets find correlations
#
# Practical implementation in Bash + Python:
#   1. _grace_contract <file>     — emit a semantic contract sidecar
#   2. _grace_clarity <file>      — score a prompt for clarity
#   3. _grace_position <file>     — emit positional context for a request
#   4. _grace_sparse_focus <file> <query> [ctx] — pick only relevant sections
#   5. _grace_normalize <file>    — normalize JSON for LLM consumption
#   6. _grace_hallucination_check <ctx> <output> — entity-presence guard
set -euo pipefail

_step_skip step_grace_semantics && return 0

[ "${SKIP_GRACE:-false}" = "true" ] && { info "GRACE semantics skipped (SKIP_GRACE=true)"; return 0; }

section "GRACE — Semantic Contracts & Clarity Metrics"

GRACE_HOME="${GRACE_HOME:-$HOME/.config/opencode/grace}"
mkdir -p "$GRACE_HOME"/{contracts,schemas,scores}

# ── 1. Semantic contract for a file ────────────────────────────────────────
_grace_contract_emit() {
  local file="${1:?file required}"
  local contract="$file.grace.yaml"
  cat > "$contract" <<EOF
# GRACE semantic contract for: $file
# Generated by har grace $(date -u +%FT%TZ)
# Read this BEFORE the file — it constrains the model's interpretation.
file: $file
generated: $(date -u +%FT%TZ)
intent: $(basename "$file")
inputs: []
outputs: []
invariants: []
position:
  in: ""
  out: ""
dependencies: []
human_review_required: true
EOF
  log "Wrote contract: $contract"
}

_grace_contract_verify() {
  local file="${1:?file required}"
  local contract="$file.grace.yaml"
  if [ -f "$contract" ]; then
    ok "Contract present: $contract"
  else
    warn "No contract: $contract"
  fi
}

# ── 2. Clarity scoring for a prompt ────────────────────────────────────────
_grace_clarity_score() {
  local file="${1:?file required}"
  python3 - <<PYEOF
import re, sys, pathlib
p = pathlib.Path("$file")
text = p.read_text(errors='ignore')
score = 50
n = len(text)
if n < 200: score += 10
elif n > 4000: score -= 15
elif n > 2000: score -= 5
have_ac = bool(re.search(r'acceptance|criteria|verify|test|must|shall', text, re.I))
have_constraints = bool(re.search(r'constraint|invariant|never|always|must not', text, re.I))
have_examples = bool(re.search(r'example|for instance|\be\.g\.', text, re.I))
if have_ac: score += 18
if have_constraints: score += 12
if have_examples: score += 8
vague = len(re.findall(r'\b(just|maybe|something|somehow|probably|some)\b', text, re.I))
score -= min(15, vague * 2)
qs = len(re.findall(r'\?', text))
score += min(8, qs)
print(f"  clarity: {max(0, min(100, score))}/100  (len={n}, AC={have_ac}, constraints={have_constraints}, examples={have_examples})")
PYEOF
}

# ── 3. Positional context for a task ───────────────────────────────────────
_grace_position() {
  local file="${1:?file required}"
  python3 - <<PYEOF
import pathlib, re
p = pathlib.Path("$file")
content = p.read_text(errors='ignore')
imports = sorted(set(re.findall(r'^(?:import |from |require\(|use )([\w./-]+)', content, re.M)))
print(f"  position: {p.name}  ({len(content)} chars)")
print(f"  imports : {len(imports)}")
for i in imports[:6]: print(f"    - {i}")
PYEOF
}

# ── 4. Sparse focus — pick relevant sections for a query ───────────────────
_grace_sparse_focus() {
  local file="${1:?file required}"
  local query="${2:?query required}"
  local ctx="${3:-3}"
  python3 - <<PYEOF
import re, pathlib
p = pathlib.Path("$file")
lines = p.read_text(errors='ignore').splitlines()
hit = False
for i, line in enumerate(lines, 1):
    if re.search(r'$query', line, re.I):
        if not hit:
            print(f"  --- $file (ctx=$ctx) ---")
            hit = True
        for j in range(max(0, i-1-$ctx), min(len(lines), i-1+$ctx+1)):
            print(f"  {j+1:4d}| {lines[j]}")
        print()
print("  (end)" if hit else "  (no matches)")
PYEOF
}

# ── 5. Normalize data for LLM consumption ─────────────────────────────────
_grace_normalize() {
  local file="${1:?file required}"
  python3 - <<PYEOF
import json, sys, pathlib
p = pathlib.Path("$file")
try:
    d = json.loads(p.read_text())
except Exception as e:
    print(f"  ERR: {e}"); sys.exit(1)
def walk(x, depth=0):
    if depth > 6: return "<deep>"
    if isinstance(x, dict):
        return {k: walk(v, depth+1) for k, v in sorted(x.items())}
    if isinstance(x, list):
        return [walk(v, depth+1) for v in x[:50]]
    if isinstance(x, str) and len(x) > 200:
        return x[:200] + f"…[+{len(x)-200}]"
    return x
print(json.dumps(walk(d), indent=2, ensure_ascii=False))
PYEOF
}

# ── 6. Hallucination guard (entity-presence) ──────────────────────────────
_grace_hallucination_check() {
  local context="${1:?context file required}"
  local output="${2:?output file required}"
  python3 - <<PYEOF
import re, sys, pathlib
ctx = pathlib.Path("$context").read_text(errors='ignore')
out = pathlib.Path("$output").read_text(errors='ignore')
def names(s):
    return set(re.findall(r'\b[A-Z][a-zA-Z0-9_-]{3,}\b', s))
ctx_names = names(ctx)
out_names = names(out)
miss = out_names - ctx_names
print(f"  context names: {len(ctx_names)}")
print(f"  output names:  {len(out_names)}")
if miss:
    print(f"  Potential hallucination: {len(miss)} name(s) not in context:")
    for n in sorted(miss)[:20]:
        print(f"    - {n}")
else:
    print("  OK: all referenced names found in context")
PYEOF
}

# ── Main ─────────────────────────────────────────────────────────────────────
_grace_contract_emit  "${1:-README.md}" 2>/dev/null || true
_grace_contract_verify "${1:-README.md}" 2>/dev/null || true
_grace_clarity_score "${1:-README.md}" 2>/dev/null || true
log "GRACE module ready — invoke via: har grace <cmd> <file> [query]"
