#!/usr/bin/env bash
# src/modes/health.sh — health check mode (36 checks, 5 sections)
# Sources: src/lib/helpers.sh, src/lib/00-core.sh must be sourced before
set -euo pipefail

echo -e "${GREEN}=== OpenCode Environment Health Check ===${NC}"
PASS=0; FAIL=0
_check() { if eval "$2" &>/dev/null; then echo -e "  ${GREEN}✓${NC} $1"; PASS=$((PASS+1)); else echo -e "  ${RED}✗${NC} $1"; FAIL=$((FAIL+1)); fi; }

section "Core CLI"
_check "Docker"         "docker --version"
_check "Java"           "java -version 2>&1 | head -1"
_check "Go"             "go version"
_check "Rust"           "rustc --version"
_check ".NET"           "dotnet --version"
_check "Kotlin"         "kotlin -version 2>&1"
_check "Zig"            "zig version 2>&1"
_check "Node.js"        "node --version"
_check "Python 3.14"    "python3.14 --version"
_check "uv"             "uv --version"
_check "bun"            "bun --version"
_check "OpenCode"       "opencode --version"
_check "Gradle"         "/usr/share/gradle/bin/gradle --version 2>&1 | head -2"
_check "Maven"          "mvn --version 2>&1 | head -1"
_check "jbang"          "jbang --version"
_check "Git"            "git --version"
_check "zsh"            "zsh --version"
_check "Chrome"         "google-chrome-stable --version 2>/dev/null | head -1"
_check "ripgrep"        "rg --version"
_check "fzf"            "fzf --version"
_check "eza"            "eza --version"
_check "bat"            "bat --version"
_check "fd"             "fdfind --version"
_check "lazygit"        "lazygit --version"
_check "zoxide"         "zoxide --version"
_check "topgrade"       "topgrade --version"
_check "abtop"          "abtop --version"
_check "chromedriver"   "chromedriver --version"
_check "bottom"         "btm --version 2>&1 | head -1"
_check "sd"             "sd --version"
_check "typos"          "typos --version"

section "MCP Servers"
_mcp_ok() { which "$1" &>/dev/null || [ -x "$HOME/.bun/bin/$1" ] || npm list -g "$2" &>/dev/null; }
_check "context7"       "_mcp_ok c7-mcp-server c7-mcp-server"
_check "filesystem"     "_mcp_ok mcp-server-filesystem @modelcontextprotocol/server-filesystem"
_check "agentic-tools"  "_mcp_ok agentic-tools-mcp @pimzino/agentic-tools-mcp"
_check "codegraph"      "_mcp_ok codegraph @colbymchenry/codegraph"
_check "playwright"     "_mcp_ok playwright-mcp @playwright/mcp"
_check "agent-browser"  "_mcp_ok agent-browser-mcp-server agent-browser-mcp-server"
_check "loopsense"      "_mcp_ok loopsense @loopsense/mcp"
_check "github"         "_mcp_ok mcp-server-github @modelcontextprotocol/server-github"
_check "postgres"       "_mcp_ok mcp-server-postgres @modelcontextprotocol/server-postgres"
_check "seq-thinking"   "_mcp_ok mcp-server-sequential-thinking @modelcontextprotocol/server-sequential-thinking"
_check "memorylayer"    "_mcp_ok memorylayer-mcp @scitrera/memorylayer-mcp-server"
_check "chrome-devtools" "_mcp_ok chrome-devtools-mcp chrome-devtools-mcp"
_check "git-mcp"         "_mcp_ok mcp-server-git mcp-server-git"
_check "memory-mcp"      "_mcp_ok mcp-server-memory @modelcontextprotocol/server-memory"
_check "fetch-mcp"       "_mcp_ok mcp-server-fetch mcp-server-fetch"
_check "time-mcp"        "_mcp_ok mcp-server-time mcp-server-time"
_check "redis-mcp"       "_mcp_ok mcp-server-redis @modelcontextprotocol/server-redis"
_check "brave-search"    "_mcp_ok brave-search-mcp brave-search-mcp"
_check "sqlite-mcp"       "uvx mcp-server-sqlite --help &>/dev/null"
_check "excalidraw-mcp"    "uvx excalidraw-architect-mcp --help &>/dev/null"
_check "context7-official" "_mcp_ok context7-mcp @upstash/context7-mcp"
_check "notion-mcp"        "_mcp_ok notion-mcp-server @notionhq/notion-mcp-server"
_check "plugin-orchestrator" "npm list -g opencode-orchestrator &>/dev/null || [ -x \"$HOME/.bun/bin/opencode-orchestrator\" ]"
_check "plugin-token-tracker" "npm list -g opencode-token-tracker &>/dev/null"
_check "plugin-notify" "npm list -g opencode-notify &>/dev/null"
_check "plugin-dcp" "npm list -g @tarquinen/opencode-dcp &>/dev/null"
_check "plugin-swarm" "npm list -g opencode-swarm &>/dev/null"
_check "plugin-auto-fallback" "npm list -g opencode-auto-fallback &>/dev/null"
_check "plugin-goal-mode" "npm list -g opencode-goal-mode &>/dev/null"
_check "plugin-vibeguard" "npm list -g opencode-vibeguard &>/dev/null"
_check "plugin-daytona" "npm list -g opencode-daytona &>/dev/null"
_check "plugin-devcontainers" "npm list -g opencode-devcontainers &>/dev/null"
_check "plugin-background-agents" "npm list -g opencode-background-agents &>/dev/null"
_check "plugin-scheduler" "npm list -g opencode-scheduler &>/dev/null"
_check "plugin-firecrawl" "npm list -g @lyculs/opencode-firecrawl &>/dev/null || [ -x \"$HOME/.bun/bin/opencode-firecrawl\" ]"
_check "plugin-otel" "npm list -g @devtheops/opencode-plugin-otel &>/dev/null"

section "LSP Servers"
_check "gopls"          "which gopls 2>/dev/null || [ -x \"$HOME/go/bin/gopls\" ]"
_check "rust-analyzer"  "which rust-analyzer"
_check "tsserver"       "which typescript-language-server"
_check "pyright"        "which pyright-langserver"
_check "bash-lsp"       "which bash-language-server"
_check "dockerfile-lsp" "which docker-langserver"
_check "css-lsp"        "which vscode-css-language-server"
_check "html-lsp"       "which vscode-html-language-server"
_check "json-lsp"       "which vscode-json-language-server"

section "Services"
_check "Muninn skills"      "[ -f ~/.config/opencode/skills/memory-read/SKILL.md ]"
_check "Skill: code-review"    "[ -f \"$HOME/projects/.opencode/skills/code-review-checklist/SKILL.md\" ] || [ -f \"$HOME/agi/.opencode/skills/code-review-checklist/SKILL.md\" ]"
_check "Skill: deployment"     "[ -f \"$HOME/projects/.opencode/skills/deployment-checklist/SKILL.md\" ] || [ -f \"$HOME/agi/.opencode/skills/deployment-checklist/SKILL.md\" ]"
_check "Skill: testing"        "[ -f \"$HOME/projects/.opencode/skills/testing-strategy/SKILL.md\" ] || [ -f \"$HOME/agi/.opencode/skills/testing-strategy/SKILL.md\" ]"
_check "Skill: context-switch"  "[ -f \"$HOME/projects/.opencode/skills/context-switching/SKILL.md\" ] || [ -f \"$HOME/agi/.opencode/skills/context-switching/SKILL.md\" ]"
_check "ChromaDB server"    "curl -sf http://127.0.0.1:8000/api/v2/heartbeat &>/dev/null"
_check "ONNX model cached"  "[ -f ~/.cache/chroma/onnx_models/all-MiniLM-L6-v2/onnx/model.onnx ]"

section "Config"
_check "opencode.json"      "[ -f ~/.config/opencode/opencode.json ]"
_check "MCPs registered"    "python3 -c \"import json; c=json.load(open('$HOME/.config/opencode/opencode.json')); m=len(c.get('mcp',{})); exit(0 if m>2 else 1)\" 2>/dev/null"
_check "AGENTS.md"          "[ -f \"${PROJECT_DIR:-$HOME/projects}/AGENTS.md\" ]"
_check "GLOBAL_WAL"           "[ -f \"${PROJECT_DIR:-$HOME/projects}/wal/state.yaml\" ]"
_check "No stale scout"     "[ ! -f \"${PROJECT_DIR:-$HOME/projects}/.opencode/agents/scout.md\" ] && [ ! -f \"$HOME/.config/opencode/agents/scout.md\" ]"

echo; log "Health: $PASS passed, $FAIL failed"
exit 0
